server:
  port: 7001
  
eureka:
  instance:
    hostname: localhost      #eureka服务端的实例名称
  client:
    register-with-eureka: false    #服务端无需注册自己
    fetch-registry: false   #表示是否从eureka-server获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与eureka-server交互的地址查询服务和注册服务都需要依赖这个地址